[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:postgresql]
command=/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/data
user=postgres
autorestart=true
stdout_logfile=/var/log/supervisor/postgresql.log
stderr_logfile=/var/log/supervisor/postgresql_error.log
environment=HOME="/var/lib/postgresql",USER="postgres"
priority=100

[program:grist]
command=node ./sandbox/supervisor.mjs
directory=/grist
user=grist
autorestart=true
stdout_logfile=/var/log/supervisor/grist.log
stderr_logfile=/var/log/supervisor/grist_error.log
environment=HOME="/grist",USER="grist"
priority=200
depends_on=postgresql