[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:postgresql]
command=/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/16/main -c config_file=/etc/postgresql/16/main/postgresql.conf
user=postgres
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/postgresql.err.log
stdout_logfile=/var/log/supervisor/postgresql.out.log

[program:grist]
command=/usr/bin/node /grist/dist/server.js
user=grist
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/grist.err.log
stdout_logfile=/var/log/supervisor/grist.out.log
environment=TYPEORM_TYPE="postgres",TYPEORM_HOST="localhost",TYPEORM_PORT="5432",TYPEORM_DATABASE="grist",TYPEORM_USERNAME="grist",TYPEORM_PASSWORD="grist123",GRIST_SPATIAL_ENABLED="true",GRIST_VECTOR_ENABLED="true",GRIST_DATA_DIR="/persist/docs",GRIST_INST_DIR="/persist",ALBERT_API_TOKEN="sk-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywidG9rZW5faWQiOjExODksImV4cGlyZXNfYXQiOjE3NzgxOTEyMDB9.mXyNfn1kLYP3hNe5lzraEHjGAbfyB-YfiNpsnp52f80"